services:
  mysql:
    image: mysql:latest
    volumes:
      - ./dev/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33060:3306

  app:
    image: ghcr.io/uzushikaminecraft/uzsk-api:main
    restart: always
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: "./config.toml"
        target: "/etc/uzsk-api/config.toml"
